[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "NODE_ENV"
  REACT_APP_BACKEND_URL = "https://ymc-pos-backend-a6db766d7240.herokuapp.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_BACKEND_URL = "https://ymc-pos-backend-a6db766d7240.herokuapp.com"
